var annotated_dup =
[
    [ "pt", "namespacept.html", [
      [ "portugal", "namespacept_1_1portugal.html", [
        [ "eid", "namespacept_1_1portugal_1_1eid.html", [
          [ "PTEID_Address", "classpt_1_1portugal_1_1eid_1_1PTEID__Address.html", "classpt_1_1portugal_1_1eid_1_1PTEID__Address" ],
          [ "PTEID_ASICContainer", "classpt_1_1portugal_1_1eid_1_1PTEID__ASICContainer.html", "classpt_1_1portugal_1_1eid_1_1PTEID__ASICContainer" ],
          [ "PTEID_ByteArray", "classpt_1_1portugal_1_1eid_1_1PTEID__ByteArray.html", "classpt_1_1portugal_1_1eid_1_1PTEID__ByteArray" ],
          [ "PTEID_Card", "classpt_1_1portugal_1_1eid_1_1PTEID__Card.html", "classpt_1_1portugal_1_1eid_1_1PTEID__Card" ],
          [ "PTEID_CardVersionInfo", "classpt_1_1portugal_1_1eid_1_1PTEID__CardVersionInfo.html", "classpt_1_1portugal_1_1eid_1_1PTEID__CardVersionInfo" ],
          [ "PTEID_CCXML_Doc", "classpt_1_1portugal_1_1eid_1_1PTEID__CCXML__Doc.html", "classpt_1_1portugal_1_1eid_1_1PTEID__CCXML__Doc" ],
          [ "PTEID_Certificate", "classpt_1_1portugal_1_1eid_1_1PTEID__Certificate.html", "classpt_1_1portugal_1_1eid_1_1PTEID__Certificate" ],
          [ "PTEID_Certificates", "classpt_1_1portugal_1_1eid_1_1PTEID__Certificates.html", "classpt_1_1portugal_1_1eid_1_1PTEID__Certificates" ],
          [ "PTEID_CMDSignatureClient", "classpt_1_1portugal_1_1eid_1_1PTEID__CMDSignatureClient.html", "classpt_1_1portugal_1_1eid_1_1PTEID__CMDSignatureClient" ],
          [ "PTEID_Config", "classpt_1_1portugal_1_1eid_1_1PTEID__Config.html", "classpt_1_1portugal_1_1eid_1_1PTEID__Config" ],
          [ "PTEID_EId", "classpt_1_1portugal_1_1eid_1_1PTEID__EId.html", "classpt_1_1portugal_1_1eid_1_1PTEID__EId" ],
          [ "PTEID_EIDCard", "classpt_1_1portugal_1_1eid_1_1PTEID__EIDCard.html", "classpt_1_1portugal_1_1eid_1_1PTEID__EIDCard" ],
          [ "PTEID_ExBadTransaction", "classpt_1_1portugal_1_1eid_1_1PTEID__ExBadTransaction.html", "classpt_1_1portugal_1_1eid_1_1PTEID__ExBadTransaction" ],
          [ "PTEID_ExBadUsage", "classpt_1_1portugal_1_1eid_1_1PTEID__ExBadUsage.html", "classpt_1_1portugal_1_1eid_1_1PTEID__ExBadUsage" ],
          [ "PTEID_ExBatchSignatureFailed", "classpt_1_1portugal_1_1eid_1_1PTEID__ExBatchSignatureFailed.html", "classpt_1_1portugal_1_1eid_1_1PTEID__ExBatchSignatureFailed" ],
          [ "PTEID_ExCardBadType", "classpt_1_1portugal_1_1eid_1_1PTEID__ExCardBadType.html", "classpt_1_1portugal_1_1eid_1_1PTEID__ExCardBadType" ],
          [ "PTEID_ExCardChanged", "classpt_1_1portugal_1_1eid_1_1PTEID__ExCardChanged.html", "classpt_1_1portugal_1_1eid_1_1PTEID__ExCardChanged" ],
          [ "PTEID_ExCardTypeUnknown", "classpt_1_1portugal_1_1eid_1_1PTEID__ExCardTypeUnknown.html", "classpt_1_1portugal_1_1eid_1_1PTEID__ExCardTypeUnknown" ],
          [ "PTEID_Exception", "classpt_1_1portugal_1_1eid_1_1PTEID__Exception.html", "classpt_1_1portugal_1_1eid_1_1PTEID__Exception" ],
          [ "PTEID_ExCertNoIssuer", "classpt_1_1portugal_1_1eid_1_1PTEID__ExCertNoIssuer.html", "classpt_1_1portugal_1_1eid_1_1PTEID__ExCertNoIssuer" ],
          [ "PTEID_ExCertNoRoot", "classpt_1_1portugal_1_1eid_1_1PTEID__ExCertNoRoot.html", "classpt_1_1portugal_1_1eid_1_1PTEID__ExCertNoRoot" ],
          [ "PTEID_ExCmdNotAllowed", "classpt_1_1portugal_1_1eid_1_1PTEID__ExCmdNotAllowed.html", "classpt_1_1portugal_1_1eid_1_1PTEID__ExCmdNotAllowed" ],
          [ "PTEID_ExCmdNotSupported", "classpt_1_1portugal_1_1eid_1_1PTEID__ExCmdNotSupported.html", "classpt_1_1portugal_1_1eid_1_1PTEID__ExCmdNotSupported" ],
          [ "PTEID_ExDocTypeUnknown", "classpt_1_1portugal_1_1eid_1_1PTEID__ExDocTypeUnknown.html", "classpt_1_1portugal_1_1eid_1_1PTEID__ExDocTypeUnknown" ],
          [ "PTEID_ExFileTypeUnknown", "classpt_1_1portugal_1_1eid_1_1PTEID__ExFileTypeUnknown.html", "classpt_1_1portugal_1_1eid_1_1PTEID__ExFileTypeUnknown" ],
          [ "PTEID_ExNoCardPresent", "classpt_1_1portugal_1_1eid_1_1PTEID__ExNoCardPresent.html", "classpt_1_1portugal_1_1eid_1_1PTEID__ExNoCardPresent" ],
          [ "PTEID_ExNoReader", "classpt_1_1portugal_1_1eid_1_1PTEID__ExNoReader.html", "classpt_1_1portugal_1_1eid_1_1PTEID__ExNoReader" ],
          [ "PTEID_ExParamRange", "classpt_1_1portugal_1_1eid_1_1PTEID__ExParamRange.html", "classpt_1_1portugal_1_1eid_1_1PTEID__ExParamRange" ],
          [ "PTEID_ExReaderSetChanged", "classpt_1_1portugal_1_1eid_1_1PTEID__ExReaderSetChanged.html", "classpt_1_1portugal_1_1eid_1_1PTEID__ExReaderSetChanged" ],
          [ "PTEID_ExReleaseNeeded", "classpt_1_1portugal_1_1eid_1_1PTEID__ExReleaseNeeded.html", "classpt_1_1portugal_1_1eid_1_1PTEID__ExReleaseNeeded" ],
          [ "PTEID_ExSOD", "classpt_1_1portugal_1_1eid_1_1PTEID__ExSOD.html", "classpt_1_1portugal_1_1eid_1_1PTEID__ExSOD" ],
          [ "PTEID_ExUnknown", "classpt_1_1portugal_1_1eid_1_1PTEID__ExUnknown.html", "classpt_1_1portugal_1_1eid_1_1PTEID__ExUnknown" ],
          [ "PTEID_Object", "classpt_1_1portugal_1_1eid_1_1PTEID__Object.html", "classpt_1_1portugal_1_1eid_1_1PTEID__Object" ],
          [ "PTEID_PACE_ERROR", "classpt_1_1portugal_1_1eid_1_1PTEID__PACE__ERROR.html", "classpt_1_1portugal_1_1eid_1_1PTEID__PACE__ERROR" ],
          [ "PTEID_PDFSignature", "classpt_1_1portugal_1_1eid_1_1PTEID__PDFSignature.html", "classpt_1_1portugal_1_1eid_1_1PTEID__PDFSignature" ],
          [ "PTEID_Photo", "classpt_1_1portugal_1_1eid_1_1PTEID__Photo.html", "classpt_1_1portugal_1_1eid_1_1PTEID__Photo" ],
          [ "PTEID_Pin", "classpt_1_1portugal_1_1eid_1_1PTEID__Pin.html", "classpt_1_1portugal_1_1eid_1_1PTEID__Pin" ],
          [ "PTEID_Pins", "classpt_1_1portugal_1_1eid_1_1PTEID__Pins.html", "classpt_1_1portugal_1_1eid_1_1PTEID__Pins" ],
          [ "PTEID_PublicKey", "classpt_1_1portugal_1_1eid_1_1PTEID__PublicKey.html", "classpt_1_1portugal_1_1eid_1_1PTEID__PublicKey" ],
          [ "PTEID_ReaderContext", "classpt_1_1portugal_1_1eid_1_1PTEID__ReaderContext.html", "classpt_1_1portugal_1_1eid_1_1PTEID__ReaderContext" ],
          [ "PTEID_ReaderSet", "classpt_1_1portugal_1_1eid_1_1PTEID__ReaderSet.html", "classpt_1_1portugal_1_1eid_1_1PTEID__ReaderSet" ],
          [ "PTEID_SigningDevice", "interfacept_1_1portugal_1_1eid_1_1PTEID__SigningDevice.html", "interfacept_1_1portugal_1_1eid_1_1PTEID__SigningDevice" ],
          [ "PTEID_SigningDeviceFactory", "classpt_1_1portugal_1_1eid_1_1PTEID__SigningDeviceFactory.html", "classpt_1_1portugal_1_1eid_1_1PTEID__SigningDeviceFactory" ],
          [ "PTEID_SigningDeviceProxy", "classpt_1_1portugal_1_1eid_1_1PTEID__SigningDeviceProxy.html", "classpt_1_1portugal_1_1eid_1_1PTEID__SigningDeviceProxy" ],
          [ "PTEID_SmartCard", "classpt_1_1portugal_1_1eid_1_1PTEID__SmartCard.html", "classpt_1_1portugal_1_1eid_1_1PTEID__SmartCard" ],
          [ "PTEID_Sod", "classpt_1_1portugal_1_1eid_1_1PTEID__Sod.html", "classpt_1_1portugal_1_1eid_1_1PTEID__Sod" ],
          [ "PTEID_XmlUserRequestedInfo", "classpt_1_1portugal_1_1eid_1_1PTEID__XmlUserRequestedInfo.html", "classpt_1_1portugal_1_1eid_1_1PTEID__XmlUserRequestedInfo" ]
        ] ]
      ] ]
    ] ]
];